logging:
    level:
        ROOT: DEBUG
        com.comcast.helloworld: DEBUG

spring:
    application:
        name: HelloWorld
    jackson:
        serialization.indent_output: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        platform: h2
        url: jdbc:h2:mem:helloworld;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: HelloWorld
        password:
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

server:
    port: 8080

application:
    restUrl:
      userMessage: https://jsonplaceholder.typicode.com/posts